## Functions and variables

In [18]:
fn main_int():
    var x = 1
    x += 1
    print("Integer x: ", x)

main_int()

fn main_str():
    var x: String = 1
    x += 1
    print("String x: ", x)

main_str()

Integer x:  2
String x:  11


In [21]:
fn add(x: Int, y: Int) -> Int:
    return x + y

z = add(1, 2)
print(z)

3


In [23]:
# borrowed & inout

fn add_inout(inout x: Int, inout y: Int) -> Int:
    x += 1
    y += 1
    return x + y

var a = 1
var b = 2
c = add_inout(a, b)
print(a)
print(b)
print(c)

2
3
5


In [28]:
# owned

fn set_fire(owned text: String) -> String:
    text += "🔥"
    return text

fn mojo():
    var a: String = "mojo"
    var b = set_fire(a)
    print(a)
    print(b)

mojo()

mojo
mojo🔥


In [31]:
# structs

struct Point:
    var x: Int
    var y: Int

    fn __init__(inout self, x: Int, y: Int):
        self.x = x
        self.y = y

    fn dump(self):
        print("Point: ", self.x, ", ", self.y)

fn main_struct():
    var p = Point(1, 2)
    p.dump()

main_struct()


Point:  1 ,  2


In [33]:
# python

from python import Python

var np = Python.import_module("numpy")

ar = np.arange(15).reshape(3, 5)
print(ar)
print(ar.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
