In [10]:
import numpy as np
import math

In [11]:
vals = np.array([[8, 4], [4, 2], [3, 9], [8, 8], [0, 8]])
labels = np.array([0, 1, 0, 0, 0, 1])


def scaling(vals):
    min = np.min(vals, axis=0)
    max = np.max(vals, axis=0)
    x_sc = (vals - min) / (max - min)
    return x_sc


xsc = scaling(vals)
x = np.array([3, 3])
x_sc = (x - np.min(vals, axis=0)) / (np.max(vals, axis=0) - np.min(vals, axis=0))


def knn(X, y, x, k=3):
    rho = np.sum((x - X) ** 2, axis=1)
    print(rho)
    result = []
    body = []
    for i in range(k):
        nejmen = np.argmin(rho)
        result.append(y[nejmen])
        print(vals[nejmen])
        rho[nejmen] = np.infty
    return result


knn(xsc, labels, x_sc, 3)

rho = np.sum((x - xsc) ** 2, axis=1)
result = []
body = []
for i in range(3):
    nejmen = np.argmin(rho)
    result.append(labels[nejmen])
    print(labels[nejmen])
    rho[nejmen] = np.infty
print(result)

[0.41103316 0.03603316 0.73469388 0.90082908 0.65082908]
[4 2]
[8 4]
[0 8]
0
0
0
[0, 0, 0]


In [12]:
# vzdalenost bodu
# math.dist(np.array(np.random.choice(5,2)), np.array(np.random.choice(5,2)))

vals = np.array([[8, 4], [4, 2], [3, 9], [8, 8], [0, 8]])
labels = np.array([0, 1, 0, 0, 0, 1])

print(vals)

[[8 4]
 [4 2]
 [3 9]
 [8 8]
 [0 8]]


In [13]:
# škálování


def scaling(vals):
    min = np.min(vals, axis=0)
    max = np.max(vals, axis=0)
    x_sc = (vals - min) / (max - min)
    return x_sc


xsc = scaling(vals)
print(xsc)
print(min)

[[1.         0.28571429]
 [0.5        0.        ]
 [0.375      1.        ]
 [1.         0.85714286]
 [0.         0.85714286]]
<built-in function min>


In [14]:
# knn
# X - matice
# y - labely
# x - testovaci bod
x = np.array([3, 3])
x_sc = (x - np.min(vals, axis=0)) / (np.max(vals, axis=0) - np.min(vals, axis=0))


def knn(X, y, x, k=3):
    rho = np.sum((x - X) ** 2, axis=1)
    print(rho)
    result = []
    body = []
    for i in range(k):
        nejmen = np.argmin(rho)
        result.append(y[nejmen])
        print(vals[nejmen])
        rho[nejmen] = np.infty
    return result


knn(xsc, labels, x_sc, 3)

[0.41103316 0.03603316 0.73469388 0.90082908 0.65082908]
[4 2]
[8 4]
[0 8]


[1, 0, 0]

In [15]:
rho = np.sum((x - xsc) ** 2, axis=1)
result = []
body = []
for i in range(3):
    nejmen = np.argmin(rho)
    result.append(labels[nejmen])
    print(labels[nejmen])
    rho[nejmen] = np.infty
print(result)

0
0
0
[0, 0, 0]
